In [4]:
#numerical python
#python library for perfoming numerical computations effectively and efficiently
#built on C lang

In [5]:
import time
import numpy as np

In [6]:
x = np.random.random(100000000) 
#random model generally generates 
#x random float numbers between 0 and 1

In [7]:
start = time.time()
sum(x) / len(x)
print( time.time() - start) #time used by python for the computation

13.013996601104736


In [8]:
start = time.time()
np.mean(x)
print(time.time() - start)

0.14797139167785645


In [9]:
#generate a random integer 
from random import randrange
print(randrange(10))

3


In [10]:
y = np.random.random(20)
print(y)

[0.58950138 0.20805667 0.64192062 0.32006089 0.31502589 0.50027945
 0.33981417 0.3515836  0.31664537 0.56108233 0.9831286  0.98041741
 0.21954783 0.4387519  0.30898709 0.2863497  0.89405159 0.30218621
 0.31844668 0.81378855]


# Creating ndarrays (n-dimensional array) with numpy


In [11]:
#Numpy ndarrays (n-dimensional arrays)
import numpy as np
x = np.array([1, 2, 3, 4, 5])

In [12]:
print(x)
print(type(x)) #returns the type of element x is

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [13]:
x.dtype #returns datatype of elements in x

dtype('int32')

In [14]:
x.shape #returns a tuple represnting the dimension(s) of the array

(5,)

In [15]:
y = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15]])
print(y)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]]


In [16]:
y.shape

(5, 3)

In [17]:
y.size

15

In [18]:
z = np.array(['Hello', 'World'])
print(z)

['Hello' 'World']


In [19]:
print('shape: ', z.shape)
print('type: ', type(z))
print('dtype: ', z.dtype)

shape:  (2,)
type:  <class 'numpy.ndarray'>
dtype:  <U5


In [20]:
v = np.array([1, 2, 'World'])
print(v)
print('shape: ', v.shape)
print('type: ', type(v))
print('dtype: ', v.dtype)

['1' '2' 'World']
shape:  (3,)
type:  <class 'numpy.ndarray'>
dtype:  <U11


In [21]:
z.dtype

dtype('<U5')

## Exercise

In [22]:
# create a 4x4 ndarray with consecutive even numbers
# from 2 to 32 inclusive
X = np.arange(2,34,2).reshape(4,4)
print(X)

[[ 2  4  6  8]
 [10 12 14 16]
 [18 20 22 24]
 [26 28 30 32]]


In [23]:
XX = np.linspace(2, 32, 16).reshape(4,4)
print(XX)

[[ 2.  4.  6.  8.]
 [10. 12. 14. 16.]
 [18. 20. 22. 24.]
 [26. 28. 30. 32.]]


In [24]:
x = np.array([1, 2, 3, 4, 5])
print(x)

[1 2 3 4 5]


# Acessing array elements by index

In [25]:
print("1st element:", x[0])
print("last element:", x[4])

1st element: 1
last element: 5


In [26]:
print("1st element:", x[-5])
print("last element:", x[-1])

1st element: 1
last element: 5


In [27]:
print(x[-3:])

[3 4 5]


In [28]:
x[3] = 20
print(x)

[ 1  2  3 20  5]


In [29]:
b = np.arange(1, 10).reshape(3, 3)
print(b)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [30]:
print("Element at (0, 0):", b[0, 0])
print("Element at (0, 2):", b[0, 2])

Element at (0, 0): 1
Element at (0, 2): 3


In [31]:
b[1, 2] = 26
print(b)

[[ 1  2  3]
 [ 4  5 26]
 [ 7  8  9]]


#  Deleting array elements

In [32]:
c = np.array([1, 2, 3, 4, 5])
c = np.delete(c, [0, 4])
print(c)

[2 3 4]


In [33]:
d = np.arange(1, 10).reshape(3, 3)
e = np.delete(d, 0, axis = 0)
print(e)

[[4 5 6]
 [7 8 9]]


In [34]:
f = np.delete(e, 1, axis = 1)
print(f)

[[4 6]
 [7 9]]


# Appending elements to an array

In [35]:
x = np.array([1, 2, 3, 4, 5])
x = np.append(x, 6)
print(x)

[1 2 3 4 5 6]


In [36]:
x = np.append(x, (7, 8, 9))
print(x)

[1 2 3 4 5 6 7 8 9]


In [37]:
y = np.arange(1, 10).reshape(3, 3)
print(y)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [38]:
y = np.append(y, [[10, 11, 12]], axis = 0)
print(y)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [39]:
y = np.append(y, [['a'], ['b'], ['c'], ['d']], axis = 1)
print(y)

[['1' '2' '3' 'a']
 ['4' '5' '6' 'b']
 ['7' '8' '9' 'c']
 ['10' '11' '12' 'd']]


# Inserting elements into an array

In [40]:
a = np.array([1, 2, 3, 4, 5])
b = np.insert(a, 2, [98, 99])
print(b)

[ 1  2 98 99  3  4  5]


In [41]:
a = np.array([[1, 2, 3], [7, 8, 9]])
a = np.insert(a, 1, [4, 5, 6], axis = 0)
print(a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [42]:
a = np.insert(a, 1, [12, 14, 15], axis = 1)
print(a)

[[ 1 12  2  3]
 [ 4 14  5  6]
 [ 7 15  8  9]]


# Stacking arrays vertically and horizontally

In [43]:
x = np.array([1, 2, 3])
y = np.array([4, 5, 6])
z = np.vstack((x, y))
print(z)

[[1 2 3]
 [4 5 6]]


In [44]:
k = np.hstack((x, y))
print(k)

[1 2 3 4 5 6]


# Slicing arrays

In [45]:
x = np.arange(1, 21).reshape(4, 5)
print(x)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [46]:
y = x[1:4, 2:5] 
#from row 1 to 3, column 2 to 4
print(y)

[[ 8  9 10]
 [13 14 15]
 [18 19 20]]


In [47]:
z = x[:2, :3]
# from begining to 2nd row, begining to 3 column
print(z)

[[1 2 3]
 [6 7 8]]


In [48]:
z[1, 1] = 39
print(z)

[[ 1  2  3]
 [ 6 39  8]]


In [49]:
print(x)

[[ 1  2  3  4  5]
 [ 6 39  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [50]:
x = np.arange(20).reshape(4, 5)
print(x)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


In [51]:
y = x[1:, 2:].copy()
# copy creates a new array whereas normal slicing just creates a representation
# of the original array, and a change in the sliced array affects the
# original array but that isn't the case when you use copy
print(y)

[[ 7  8  9]
 [12 13 14]
 [17 18 19]]


In [52]:
y[2, 2] = 30
print(y)

[[ 7  8  9]
 [12 13 14]
 [17 18 30]]


In [53]:
print(x)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


In [54]:
indices = np.array([1, 3])
print(indices)

[1 3]


In [55]:
y = x[indices, :]
print(y)

[[ 5  6  7  8  9]
 [15 16 17 18 19]]


In [56]:
z = x[:, indices]
print(z)

[[ 1  3]
 [ 6  8]
 [11 13]
 [16 18]]


In [57]:
d = np.diag(x)
print(d)

[ 0  6 12 18]


In [58]:
e = np.diag(x, k = 1)
# k is the leading diagonal, at index 0 by default
# k = 1 is the diagonal above the leading diagonal
print(e)

[ 1  7 13 19]


In [59]:
f = np.diag(x, k = -1) 
# k = -1 is the diagonal below the leading diagonal
print(f)

[ 5 11 17]


# Get unique array values


In [60]:
j = np.array([[1, 2, 3], [5, 2, 6], [7, 3, 5]])
print(np.unique(j))
# get the elements of the array disregarding repeated values

[1 2 3 5 6 7]


# Boolean indexing, set operations, sorting


In [62]:
x = np.arange(25).reshape(5, 5)
print(x)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


In [65]:
print(x[x > 10])
# prints values in "x" greater than 10

[11 12 13 14 15 16 17 18 19 20 21 22 23 24]


In [66]:
print(x[x < 7])
# prints values in "x" less than 7

[0 1 2 3 4 5 6]


In [70]:
print(x[(x >10) & (x < 18)])

[11 12 13 14 15 16 17]


In [71]:
x[(x >10) & (x < 18)] = -1
print(x)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 -1 -1 -1 -1]
 [-1 -1 -1 18 19]
 [20 21 22 23 24]]


In [74]:
a = np.array([1, 2, 3, 4, 5])
b = np.array([6, 7, 2, 9, 1])
print("The intersection of a and b is:", np.intersect1d(a, b))
print("The union of a and b is:", np.union1d(a, b))
print("The difference between a and b is:", np.setdiff1d(a, b))

The intersection of a and b is: [1 2]
The union of a and b is: [1 2 3 4 5 6 7 9]
The difference between a and b is: [3 4 5]


### List of random integers in a given range
njangi = np.random.randint(1, 15, size = 14)
print(njangi)

In [91]:
x = np.random.randint(1, 11, size = (10))
print(x)

[1 3 9 6 4 5 3 2 9 2]


In [93]:
print(np.sort(x))
print(x)

[1 2 2 3 3 4 5 6 9 9]
[1 3 9 6 4 5 3 2 9 2]


In [94]:
print(np.sort(np.unique(x)))

[1 2 3 4 5 6 9]


In [95]:
print(x)

[1 3 9 6 4 5 3 2 9 2]


Using Numpy for sorting does not change the original array
Unlike using sort() method which changes the original array


In [96]:
x.sort()
print(x)

[1 2 2 3 3 4 5 6 9 9]


In [97]:
o = np.random.randint(1, 11, size = (5, 5))
print(o)

[[ 9 10  6  3  8]
 [ 3  4 10 10  1]
 [ 6  3 10  6  2]
 [ 8  2  3  1  3]
 [ 8  1  2  6  6]]


In [100]:
print(np.sort(o, axis = 1))

[[ 3  6  8  9 10]
 [ 1  3  4 10 10]
 [ 2  3  6  6 10]
 [ 1  2  3  3  8]
 [ 1  2  6  6  8]]
