In [1]:
#numerical python
#python library for perfoming numerical computations effectively and efficiently
#built on C lang

In [2]:
import time
import numpy as np

In [3]:
x = np.random.random(100000000) 
#random model generally generates 
#x random float numbers between 0 and 1

In [4]:
start = time.time()
sum(x) / len(x)
print( time.time() - start) #time used by python for the computation

13.6609947681427


In [5]:
start = time.time()
np.mean(x)
print(time.time() - start)

0.14797639846801758


In [6]:
#generate a random integer 
from random import randrange
print(randrange(10))

9


In [7]:
y = np.random.random(20)
print(y)

[0.9556383  0.11819176 0.47063939 0.97730676 0.10625489 0.3928015
 0.02103791 0.77787713 0.24914857 0.72396498 0.03973844 0.65877313
 0.63795742 0.51622964 0.55585529 0.15871932 0.99535056 0.82987133
 0.65742741 0.39442865]


# Creating ndarrays (n-dimensional array) with numpy


In [8]:
#Numpy ndarrays (n-dimensional arrays)
import numpy as np
x = np.array([1, 2, 3, 4, 5])

In [9]:
print(x)
print(type(x)) #returns the type of element x is

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [10]:
x.dtype #returns datatype of elements in x

dtype('int32')

In [11]:
x.shape #returns a tuple represnting the dimension(s) of the array

(5,)

In [12]:
y = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15]])
print(y)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]]


In [13]:
y.shape

(5, 3)

In [14]:
y.size

15

In [15]:
z = np.array(['Hello', 'World'])
print(z)

['Hello' 'World']


In [16]:
print('shape: ', z.shape)
print('type: ', type(z))
print('dtype: ', z.dtype)

shape:  (2,)
type:  <class 'numpy.ndarray'>
dtype:  <U5


In [17]:
v = np.array([1, 2, 'World'])
print(v)
print('shape: ', v.shape)
print('type: ', type(v))
print('dtype: ', v.dtype)

['1' '2' 'World']
shape:  (3,)
type:  <class 'numpy.ndarray'>
dtype:  <U11


In [18]:
z.dtype

dtype('<U5')

## Exercise

In [19]:
# create a 4x4 ndarray with consecutive even numbers
# from 2 to 32 inclusive
X = np.arange(2,34,2).reshape(4,4)
print(X)

[[ 2  4  6  8]
 [10 12 14 16]
 [18 20 22 24]
 [26 28 30 32]]


In [20]:
XX = np.linspace(2, 32, 16).reshape(4,4)
print(XX)

[[ 2.  4.  6.  8.]
 [10. 12. 14. 16.]
 [18. 20. 22. 24.]
 [26. 28. 30. 32.]]


In [21]:
x = np.array([1, 2, 3, 4, 5])
print(x)

[1 2 3 4 5]


# Acessing array elements by index

In [22]:
print("1st element:", x[0])
print("last element:", x[4])

1st element: 1
last element: 5


In [23]:
print("1st element:", x[-5])
print("last element:", x[-1])

1st element: 1
last element: 5


In [24]:
print(x[-3:])

[3 4 5]


In [25]:
x[3] = 20
print(x)

[ 1  2  3 20  5]


In [26]:
b = np.arange(1, 10).reshape(3, 3)
print(b)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [27]:
print("Element at (0, 0):", b[0, 0])
print("Element at (0, 2):", b[0, 2])

Element at (0, 0): 1
Element at (0, 2): 3


In [28]:
b[1, 2] = 26
print(b)

[[ 1  2  3]
 [ 4  5 26]
 [ 7  8  9]]


#  Deleting array elements

In [29]:
c = np.array([1, 2, 3, 4, 5])
c = np.delete(c, [0, 4])
print(c)

[2 3 4]


In [30]:
d = np.arange(1, 10).reshape(3, 3)
e = np.delete(d, 0, axis = 0)
print(e)

[[4 5 6]
 [7 8 9]]


In [31]:
f = np.delete(e, 1, axis = 1)
print(f)

[[4 6]
 [7 9]]


# Appending elements to an array

In [32]:
x = np.array([1, 2, 3, 4, 5])
x = np.append(x, 6)
print(x)

[1 2 3 4 5 6]


In [33]:
x = np.append(x, (7, 8, 9))
print(x)

[1 2 3 4 5 6 7 8 9]


In [34]:
y = np.arange(1, 10).reshape(3, 3)
print(y)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [35]:
y = np.append(y, [[10, 11, 12]], axis = 0)
print(y)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [36]:
y = np.append(y, [['a'], ['b'], ['c'], ['d']], axis = 1)
print(y)

[['1' '2' '3' 'a']
 ['4' '5' '6' 'b']
 ['7' '8' '9' 'c']
 ['10' '11' '12' 'd']]


# Inserting elements into an array

In [37]:
a = np.array([1, 2, 3, 4, 5])
b = np.insert(a, 2, [98, 99])
print(b)

[ 1  2 98 99  3  4  5]


In [38]:
a = np.array([[1, 2, 3], [7, 8, 9]])
a = np.insert(a, 1, [4, 5, 6], axis = 0)
print(a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [39]:
a = np.insert(a, 1, [12, 14, 15], axis = 1)
print(a)

[[ 1 12  2  3]
 [ 4 14  5  6]
 [ 7 15  8  9]]


# Stacking arrays vertically and horizontally

In [40]:
x = np.array([1, 2, 3])
y = np.array([4, 5, 6])
z = np.vstack((x, y))
print(z)

[[1 2 3]
 [4 5 6]]


In [41]:
k = np.hstack((x, y))
print(k)

[1 2 3 4 5 6]


# Slicing arrays

In [42]:
x = np.arange(1, 21).reshape(4, 5)
print(x)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [43]:
y = x[1:4, 2:5] 
#from row 1 to 3, column 2 to 4
print(y)

[[ 8  9 10]
 [13 14 15]
 [18 19 20]]


In [44]:
z = x[:2, :3]
# from begining to 2nd row, begining to 3 column
print(z)

[[1 2 3]
 [6 7 8]]


In [45]:
z[1, 1] = 39
print(z)

[[ 1  2  3]
 [ 6 39  8]]


In [46]:
print(x)

[[ 1  2  3  4  5]
 [ 6 39  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [47]:
x = np.arange(20).reshape(4, 5)
print(x)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


In [48]:
y = x[1:, 2:].copy()
# copy creates a new array whereas normal slicing just creates a representation
# of the original array, and a change in the sliced array affects the
# original array but that isn't the case when you use copy
print(y)

[[ 7  8  9]
 [12 13 14]
 [17 18 19]]


In [49]:
y[2, 2] = 30
print(y)

[[ 7  8  9]
 [12 13 14]
 [17 18 30]]


In [50]:
print(x)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


In [51]:
indices = np.array([1, 3])
print(indices)

[1 3]


In [52]:
y = x[indices, :]
print(y)

[[ 5  6  7  8  9]
 [15 16 17 18 19]]


In [53]:
z = x[:, indices]
print(z)

[[ 1  3]
 [ 6  8]
 [11 13]
 [16 18]]


In [54]:
d = np.diag(x)
print(d)

[ 0  6 12 18]


In [55]:
e = np.diag(x, k = 1)
# k is the leading diagonal, at index 0 by default
# k = 1 is the diagonal above the leading diagonal
print(e)

[ 1  7 13 19]


In [56]:
f = np.diag(x, k = -1) 
# k = -1 is the diagonal below the leading diagonal
print(f)

[ 5 11 17]


# Get unique array values


In [57]:
j = np.array([[1, 2, 3], [5, 2, 6], [7, 3, 5]])
print(np.unique(j))
# get the elements of the array disregarding repeated values

[1 2 3 5 6 7]


# Boolean indexing, set operations, sorting


In [58]:
x = np.arange(25).reshape(5, 5)
print(x)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


In [59]:
print(x[x > 10])
# prints values in "x" greater than 10

[11 12 13 14 15 16 17 18 19 20 21 22 23 24]


In [60]:
print(x[x < 7])
# prints values in "x" less than 7

[0 1 2 3 4 5 6]


In [61]:
print(x[(x >10) & (x < 18)])

[11 12 13 14 15 16 17]


In [62]:
x[(x >10) & (x < 18)] = -1
print(x)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 -1 -1 -1 -1]
 [-1 -1 -1 18 19]
 [20 21 22 23 24]]


In [63]:
a = np.array([1, 2, 3, 4, 5])
b = np.array([6, 7, 2, 9, 1])
print("The intersection of a and b is:", np.intersect1d(a, b))
print("The union of a and b is:", np.union1d(a, b))
print("The difference between a and b is:", np.setdiff1d(a, b))

The intersection of a and b is: [1 2]
The union of a and b is: [1 2 3 4 5 6 7 9]
The difference between a and b is: [3 4 5]


### List of random integers in a given range
njangi = np.random.randint(1, 15, size = 14)
print(njangi)

In [64]:
x = np.random.randint(1, 11, size = (10))
print(x)

[ 5  7 10  4 10  2  5  8  3  4]


In [65]:
print(np.sort(x))
print(x)

[ 2  3  4  4  5  5  7  8 10 10]
[ 5  7 10  4 10  2  5  8  3  4]


In [66]:
print(np.sort(np.unique(x)))

[ 2  3  4  5  7  8 10]


In [67]:
print(x)

[ 5  7 10  4 10  2  5  8  3  4]


Using Numpy for sorting does not change the original array
Unlike using sort() method which changes the original array


In [68]:
x.sort()
print(x)

[ 2  3  4  4  5  5  7  8 10 10]


In [69]:
o = np.random.randint(1, 11, size = (5, 5))
print(o)

[[ 7  2  9  6  2]
 [ 8  2  8  4 10]
 [ 5  1  8  6  8]
 [10  8 10  7  6]
 [10  4  2  8  3]]


In [70]:
print(np.sort(o, axis = 1))

[[ 2  2  6  7  9]
 [ 2  4  8  8 10]
 [ 1  5  6  8  8]
 [ 6  7  8 10 10]
 [ 2  3  4  8 10]]


In [71]:
X = np.arange(1, 26).reshape(5, 5)
print(X)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


In [72]:
Y = X[X % 2 != 0]
print(Y)

[ 1  3  5  7  9 11 13 15 17 19 21 23 25]


# Broadcasting and Arithmetic operations

In [75]:
x = np.array([1, 2, 3, 4])
y = np.array([5, 6, 7, 8])
print(x + y)
print(np.add(x, y))

[ 6  8 10 12]
[ 6  8 10 12]


In [77]:
print(y - x)
print(np.subtract(y, x))
print(x * y)
print(np.multiply(x, y))
print(y / x)
print(np.divide(y, x))

[4 4 4 4]
[4 4 4 4]
[ 5 12 21 32]
[ 5 12 21 32]
[5.         3.         2.33333333 2.        ]
[5.         3.         2.33333333 2.        ]


In [79]:
print(np.sqrt(x))

[1.         1.41421356 1.73205081 2.        ]


In [80]:
print(np.power(x, 2))

[ 1  4  9 16]


In [82]:
X = np.arange(1, 5).reshape(2, 2)
print(X)
X.mean()

[[1 2]
 [3 4]]


2.5

In [87]:
print(X.mean(axis = 0))
print(X.mean(axis = 1))

[2. 3.]
[1.5 3.5]


In [89]:
print(X.sum())
print(X.sum(axis = 0))
print(X.sum(axis = 1))

10
[4 6]
[3 7]


In [91]:
X.std()

1.118033988749895

In [92]:
np.median(X)

2.5

In [93]:
X.max()


4

In [94]:
x.min()

1

In [95]:
print(3 + X)
print(X - 3)
print(3 * X)
print(3 / X)

[[4 5]
 [6 7]]
[[-2 -1]
 [ 0  1]]
[[ 3  6]
 [ 9 12]]
[[3.   1.5 ]
 [1.   0.75]]


In [98]:
print(np.ones((4, 4)))

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [99]:
print(np.arange(1, 5))

[1 2 3 4]


In [101]:
Z = np.ones((4, 4)) * np.arange(1, 5)
print(Z)

[[1. 2. 3. 4.]
 [1. 2. 3. 4.]
 [1. 2. 3. 4.]
 [1. 2. 3. 4.]]
